"""
generator.py

Generates answers using the configured Large Language Model.

Flow:
    Prompt
      │
      ▼
   OpenAI LLM
      │
      ▼
 Generated Answer

Author: Jaya Bharath
"""

from llm.llm_manager import LLMManager


class Generator:
    """
    Generates responses from the Large Language Model.
    """

    def __init__(self):
        """
        Initialize the LLM Manager.
        """

        self.llm = LLMManager()

    # ==========================================================
    # Generate Response
    # ==========================================================

    def generate(self, prompt: str) -> str:
        """
        Generate an answer using the LLM.

        Parameters
        ----------
        prompt : str
            Prompt generated by PromptBuilder.

        Returns
        -------
        str
            Generated answer.
        """

        response = self.llm.ask(prompt)

        return response

    # ==========================================================
    # Callable Interface
    # ==========================================================

    def __call__(self, prompt: str) -> str:
        """
        Allows the Generator object to be called directly.

        Example
        -------
        answer = generator(prompt)
        """

        return self.generate(prompt)