"""
response.py

Data model representing the response generated by the RAG pipeline.

Author: Jaya Bharath
"""

from dataclasses import dataclass, field
from typing import List, Dict


@dataclass
class Response:
    """
    Represents the final response from the chatbot.

    Attributes:
        question: User's question.
        answer: Generated answer from the LLM.
        sources: List of retrieved source documents.
        processing_time: Total execution time.
        retrieved_chunks: Number of chunks retrieved.
    """

    question: str
    answer: str

    sources: List[Dict] = field(default_factory=list)

    processing_time: float = 0.0

    retrieved_chunks: int = 0

    def add_source(self, source: Dict):
        """
        Add a retrieved source.
        """
        self.sources.append(source)

    def number_of_sources(self):
        """
        Return total retrieved sources.
        """
        return len(self.sources)

    def to_dict(self):
        """
        Convert Response object into dictionary.
        """

        return {
            "question": self.question,
            "answer": self.answer,
            "sources": self.sources,
            "processing_time": self.processing_time,
            "retrieved_chunks": self.retrieved_chunks,
        }

    def __str__(self):

        return (
            f"Response("
            f"question='{self.question[:40]}...', "
            f"sources={len(self.sources)}, "
            f"time={self.processing_time:.2f}s)"
        )