"""
response.py

Represents the final response generated by the RAG pipeline.

Author: Jaya Bharath
"""

from dataclasses import dataclass, field
from typing import List, Dict


@dataclass
class Response:
    """
    Final chatbot response.
    """

    question: str

    answer: str

    sources: List[Dict] = field(default_factory=list)

    processing_time: float = 0.0

    retrieved_chunks: int = 0

    # ==========================================================
    # Source Operations
    # ==========================================================

    def add_source(
        self,
        source: Dict
    ) -> None:
        """
        Add a source document.
        """

        self.sources.append(source)

    def number_of_sources(self) -> int:
        """
        Return total number of retrieved sources.
        """

        return len(self.sources)

    # ==========================================================
    # Utility
    # ==========================================================

    def to_dict(self) -> Dict:
        """
        Convert response to dictionary.
        """

        return {
            "question": self.question,
            "answer": self.answer,
            "sources": self.sources,
            "processing_time": self.processing_time,
            "retrieved_chunks": self.retrieved_chunks,
        }

    def __repr__(self) -> str:

        return (
            f"Response("
            f"question='{self.question[:40]}...', "
            f"sources={len(self.sources)}, "
            f"time={self.processing_time:.2f}s)"
        )